---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.db.volume.storageClassName }}
  capacity:
    storage: {{ .Values.db.volume.storage }}
  accessModes:
    - {{ .Values.db.volume.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
