---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
  storageClassName: {{ .Values.db.volume.storageClassName }}
  accessModes:
    - {{ .Values.db.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.volume.storage }}
