---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
  labels:
    app: {{ .Release.Name }}-db
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      protocol: TCP
