---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: "TCP"
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: LoadBalancer
