---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  labels:
    app: {{ .Release.Name }}-db
data:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PORT: {{ .Values.db.port | quote }}
