---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-rest-api
  name: python-rest-api
  namespace: test
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: python-rest-api
  type: LoadBalancer