---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-rest-api
  template:
    metadata:
      labels:
        app: python-rest-api
    spec:
      containers:
        - name: python-rest-api
          image: docker.io/haagy/python-rest-api:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 6666
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: db-service
          envFrom:
            - configMapRef:
                name: db-config
