---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test
  template:
    metadata:
      labels:
        app: python-test
    spec:
      containers:
      - name: python-test
        image: 10.10.10.9:5000/python-test-docker:2.1
        imagePullPolicy: Always
        ports:
        - containerPort: 6666
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: db-service
        envFrom:
        - configMapRef:
            name: db-config
