---
apiVersion: v1
kind: Service
metadata:
  name: python-rest-api-service
spec:
  selector:
    app: python-rest-api
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
