{{- if not .Values.secrets.vault.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.password | default "postgres" | b64enc }}
{{ end }}
