{{- if not .Values.environment.isProd }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  database_password: {{ .Values.db.password | default "postgres" | b64enc }}
{{ end }}
